<a href="https://colab.research.google.com/github/Raihandany/PCVK_Ganjil_2023/blob/main/Week5_PCVK_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
import pandas as pd
import cv2 as cv





In [10]:
print(' Gamma Correction pada citra ')
print('----------------------------------')
try:
  gamma = int(input('Masukkan nilai Gamma: '))
except ValueError:
  print('Error, not a number')

original = cv.imread('/content/drive/MyDrive/PCVK_MM/prac_week5/female.tiff')
gamma_image = np.zeros(original.shape, original.dtype)

for y in range(original.shape[0]):
  for x in range(original.shape[1]):
      gamma_image[y,x] = 255 * ((original[y,x] / 255) ** (1/gamma))

final_frame = cv.hconcat((original, gamma_image))
print(final_frame)

 Gamma Correction pada citra 
----------------------------------
Masukkan nilai Gamma: 3
[[[ 42  46  52]
  [ 38  40  47]
  [ 34  42  50]
  ...
  [206 204 207]
  [206 207 201]
  [203 205 201]]

 [[ 43  45  55]
  [ 35  44  50]
  [ 38  40  54]
  ...
  [210 208 203]
  [208 205 203]
  [211 209 198]]

 [[ 39  42  46]
  [ 43  42  49]
  [ 55  42  52]
  ...
  [205 207 201]
  [203 204 199]
  [202 205 197]]

 ...

 [[  5   5   4]
  [  4   3   3]
  [  3   3   3]
  ...
  [141 160 157]
  [180 182 176]
  [182 189 185]]

 [[ 10   8  11]
  [ 12  11  12]
  [ 10  10  12]
  ...
  [137 164 157]
  [160 178 177]
  [180 189 186]]

 [[ 16  18  20]
  [ 16  16  19]
  [ 13  14  20]
  ...
  [139 153 152]
  [155 171 165]
  [173 186 182]]]
